# Setup

In [2]:
# Dependencies

import pandas as pd

In [3]:
# Setting to reveal up to 500 rows in notebook

pd.set_option('display.max_rows', 500)

# Functions

In [4]:
def basic_clean(a_df):
    '''Performs initial cleaning of dataframe'''
    
    a_df = a_df.drop_duplicates(keep="first")
    
    return a_df

In [5]:
def all_caps(a_df, a_list):
    '''Renders string df columns in supplied list in all caps, returns dataframe'''
    
    for col in a_list:
        a_df[col] = a_df[col].str.upper()
        
    return a_df

In [6]:
def vc(a_ser):
    '''Return value_counts().to_frame() for a series'''
    
    return a_ser.value_counts().to_frame()

In [7]:
def clean_isbns(a_ser):
    '''Renders isbn series data as str and strips unwanted chars, returns a series'''
    
    a_ser = a_ser.astype("str") 
    a_ser = a_ser.str.rstrip(".0")
    
    return a_ser

In [8]:
def clean_prices(a_ser):
    '''Strips unwanted chars from price data and renders as float, returns a series'''
    
    a_ser = a_ser.astype("str") 
    a_ser = a_ser.str.lstrip("$")
    a_ser = a_ser.str.replace(",", "", regex=False)
    a_ser = a_ser.str.replace("PRICE NOT YET AVAILABLE**", "0.01", regex=False)
    a_ser = a_ser.str.replace("PREPAID", "0.01", regex=False)
    a_ser = a_ser.apply(lambda x: float(x))

    return a_ser

# Import courses.csv into dataframe, clean and transform data

### *courses_df*

In [9]:
# This csv is large, so we need to include low-memory=False when rendering as dataframe

# NOTE: enter correct filepath for your downloaded csv file

filepath1 = "D:\\BNCollegeCourses_2022-02-05.csv"

df1 = basic_clean(pd.read_csv(filepath1, encoding="Utf-8", low_memory=False))

In [10]:
# Checking shape and dtypes of data

df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 537821 entries, 0 to 538048
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   university     537821 non-null  object
 1   store_id       380343 non-null  float64
 2   catalog_id     55691 non-null   float64
 3   campus         516255 non-null  object
 4   campus_id      537821 non-null  object
 5   term           537821 non-null  object
 6   term_id        537821 non-null  object
 7   department     537821 non-null  object
 8   department_id  537821 non-null  object
 9   course         537821 non-null  object
 10  course_id      537821 non-null  object
 11  section        537821 non-null  object
 12  section_id     537821 non-null  object
 13  scanDate       537821 non-null  object
dtypes: float64(2), object(12)
memory usage: 61.5+ MB

In [11]:
# Eliminate dupes and drop unneeded columns

df1 = df1.drop_duplicates()

df1 = df1.drop(columns=["store_id", "catalog_id", "campus", "campus_id", "term_id", "scanDate"])

In [12]:
# Reorder columns and capitalize data where appropriate

df1 = df1[["department_id", "course_id", "section_id", "university", "term", "department", "course", "section"]]

all_caps(df1, ["university", "term", "department", "course", "section"])

,department_id,course_id,section_id,university,term,department,course,section
0,334_1_9,200,1,BALL STATE UNIVERSITY,SPRING 2022,ACC,200,1
1,334_1_9,201,01,BALL STATE UNIVERSITY,SPRING 2022,ACC,201,01
2,334_1_9,201,02,BALL STATE UNIVERSITY,SPRING 2022,ACC,201,02
3,334_1_9,201,03,BALL STATE UNIVERSITY,SPRING 2022,ACC,201,03
4,334_1_9,201,04,BALL STATE UNIVERSITY,SPRING 2022,ACC,201,04
...,...,...,...,...,...,...,...,...
538044,107904486,107916807,107902500,FLORIDA INTERNATIONAL UNIVERSITY,FALL 2022,PHC,6328,RVC
538045,107904486,107916813,107902492,FLORIDA INTERNATIONAL UNIVERSITY,FALL 2022,PHC,6104C,RXD
538046,107904486,107916814,107902491,FLORIDA INTERNATIONAL UNIVERSITY,FALL 2022,PHC,6102,RXD
538047,107904486,107916814,107902490,FLORIDA INTERNATIONAL UNIVERSITY,FALL 2022,PHC,6102,RVC
538048,107904486,107916815,107902375,FLORIDA INTERNATIONAL UNIVERSITY,FALL 2022,PHC,6099,U01

In [13]:
# Examine value counts on term column to begin consolidation into categories 

vc(df1["term"])

                        term
SPRING 2022           287183
FALL 2021              67170
FALL 2022              19304
FALL 21                16880
WINTER - 2022          12627
SPRING '22             12417
WINTER 2022            12220
SUMMER 2022            11341
SPRING - 2022          10979
FALL SEMESTER 2021      9352
PANTHER BOOK PACK       9194
SPRING 2022 OPT OUT     8846
SPRING SEMEST. 2022     8631
SPRING 22               7170
SPRING '22 PULLMAN      4739
SPRING '22 ONCAMPUS     4711
SPRING TERM 2022        4379
SPRING 22 BKT BNDLE     4095
SPRING 2022 RES.        4039
ALL SUMMER TERMS        3793
MEDICAL SCHOOL 2021     2575
SPRING/SUMMER 2022      2356
WINTER QUARTER 2022     1468
FALL QUARTER 2021       1271
UCF SPRING 2022         1114
22SPDAY 1/3-4/24        1073
SPRING 22 TERM 3         839
SPRING '22 GLOBAL        716
SPRING 22 TERM 4         712
WSU SPRING 2022          625
FALL 21 SUPPLEMENT       443
21FALLS                  439
SPRING 22 SUPPLEMENT     416
21SPRGS                  410
WINTER INTERSESSION      381
SUMMER 22 TERM 5         337
VC SPRING 2022           317
SPRING22                 286
22DY03 (01/03-02/27      248
PROFESSIONAL 21/22       242
LAW SPRING - 2022        223
SEC SPRING TERM 22       220
WINTER 2021              220
FIRST SPRING 22          188
WINTER 22                179
1ST SPRING MOD 2022      162
WINTER '22               158
SPRING '22 EVERETT       151
SPRING 1 '22 ONLINE      129
2ND SPRING MOD 2022      124
WINTER SESSION 21-2       96
SPRING 2022 SEMESTE       90
SPRING TERM 3             81
SPRING TERM 4             71
WINTER SESSION 22         70
SPRING FULL TERM 22       60
MAYMESTER 2022            36
TROY PC SPRING T-3        35
22DY04 (2/28-4/24)        32
TROY PC SPRING T-4        28
SELF-PACED COURSES        22
WINTER '22 SFCC           22
21FALL2                   16
TROY PC SPRING 2022       14
21FALL1                   13
HIGH SCHOOL               13
SUMMER 22 SEMESTER        10
LATE SUMMER                8
21SPRG1                    8
FALL 22 TERM 1             2
PARALEGAL SPRING 22        1
FALL 22 SEMESTER           1

In [14]:
# Use boolean masks to consolidate into manageable term categories: FALL, WINTER, SPRING, SUMMER 

fall_mask = df1["term"].str.contains("FALL")

df1.loc[fall_mask, "term"] = "FALL"


spring_mask = df1["term"].str.contains("SPRING")

df1.loc[spring_mask, "term"] = "SPRING"


summer_mask = df1["term"].str.contains("SUMMER")

df1.loc[summer_mask, "term"] = "SUMMER"


winter_mask = df1["term"].str.contains("WINTER")

df1.loc[winter_mask, "term"] = "WINTER"


junk_mask = ~(df1["term"].isin(["FALL", "WINTER", "SPRING", "SUMMER"]))

df1.loc[junk_mask, "term"] = "JUNK"

df1 = df1.loc[~(df1["term"]=="JUNK"), :]

vc(df1["term"])

          term
SPRING  366147
FALL    114891
WINTER   27441
SUMMER   15489

In [36]:
# Render some columns as categorical data type - saves memory

# (df1["term"] 
#     .astype('category')
# )


df1.loc[ : , ("term")  ].astype("category")
df1.loc[ : , ("university")  ].astype("category")

df1.loc[ : , ("department")  ].astype("category")

df1.loc[ : , ("course")  ].astype("category")

df1.loc[ : , ("section")  ].astype("category")

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523968 entries, 0 to 523967
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   department_id  523968 non-null  object
 1   course_id      523968 non-null  object
 2   section_id     523968 non-null  object
 3   university     523968 non-null  category
 4   term           523968 non-null  category
 5   department     523968 non-null  category
 6   course         523968 non-null  category
 7   section        523968 non-null  category
dtypes: category(5), object(3)
memory usage: 20.4+ MB

In [20]:
df1 = df1.reset_index(drop=True)

In [21]:
courses_df = df1.copy()

In [22]:
courses_df

,department_id,course_id,section_id,university,term,department,course,section
0,334_1_9,200,1,BALL STATE UNIVERSITY,SPRING,ACC,200,1
1,334_1_9,201,01,BALL STATE UNIVERSITY,SPRING,ACC,201,01
2,334_1_9,201,02,BALL STATE UNIVERSITY,SPRING,ACC,201,02
3,334_1_9,201,03,BALL STATE UNIVERSITY,SPRING,ACC,201,03
4,334_1_9,201,04,BALL STATE UNIVERSITY,SPRING,ACC,201,04
...,...,...,...,...,...,...,...,...
523963,107904486,107916807,107902500,FLORIDA INTERNATIONAL UNIVERSITY,FALL,PHC,6328,RVC
523964,107904486,107916813,107902492,FLORIDA INTERNATIONAL UNIVERSITY,FALL,PHC,6104C,RXD
523965,107904486,107916814,107902491,FLORIDA INTERNATIONAL UNIVERSITY,FALL,PHC,6102,RXD
523966,107904486,107916814,107902490,FLORIDA INTERNATIONAL UNIVERSITY,FALL,PHC,6102,RVC
523967,107904486,107916815,107902375,FLORIDA INTERNATIONAL UNIVERSITY,FALL,PHC,6099,U01

In [23]:
# Render as csv file for import into PostGresSQL

courses_df.to_csv("MERGE_courses.csv", encoding="utf-8")

# 39 MB csv

# Import textbooks.csv into dataframe, clean and transform data

### *textbooks_df*

In [24]:
# This csv is large, so we need to include low-memory=False when rendering as dataframe

# NOTE: enter correct filepath for your downloaded csv file

filepath2 = "D:\\BNTextbook_2022-02-05.csv"

df2 = basic_clean(pd.read_csv(filepath2, encoding="Utf-8", low_memory=False))

In [25]:
# Checking shape and dtypes of data

df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 990727 entries, 0 to 992674
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   store_id             669440 non-null  float64
 1   catalog_id           121358 non-null  float64
 2   campus_id            990727 non-null  object
 3   term_id              990727 non-null  object
 4   department_id        990727 non-null  object
 5   course_id            990727 non-null  object
 6   section_id           990727 non-null  object
 7   title                645255 non-null  object
 8   edition              633950 non-null  object
 9   publisher            644969 non-null  object
 10  book_type            645255 non-null  object
 11  book_url             645255 non-null  object
 12  book_id              645255 non-null  object
 13  no_textbook_message  345472 non-null  object
 14  recommend_type       641580 non-null  object
 15  ISBN                 644811 non-null  float64
 16  price                645255 non-null  object
 17  scanDate             990727 non-null  object
dtypes: float64(3), object(15)
memory usage: 143.6+ MB

In [26]:
# Eliminate dupes and drop unneeded columns

df2 = df2.drop_duplicates()

df2 = df2.drop(columns=\
    ["store_id", "catalog_id", "campus_id", "term_id", "book_id",\
     "no_textbook_message", "recommend_type", "scanDate"])

In [27]:
# Reorder columns and capitalize data where appropriate

all_caps(df2, ["title", "edition", "publisher", "book_type", "price"])

,department_id,course_id,section_id,title,edition,publisher,book_type,book_url,ISBN,price
0,334_1_9,200,1,CENGAGE UNLIMITED - ACCESS (1 SEMESTER),18,CENGAGE U,DIGITAL PURCHASE,https://bsu.bncollege.com/c/Cengage-Unlimited-...,9.780358e+12,$119.99
1,334_1_9,201,01,FINANCIAL ACCOUNTING: INFORMATION FOR DECISION...,10TH 21,MCG CUSTOM,NEW PRINT,https://bsu.bncollege.com/c/Financial-Accounti...,9.781264e+12,$107.90
2,334_1_9,201,02,FINANCIAL ACCOUNTING: INFORMATION FOR DECISION...,10TH 21,MCG CUSTOM,NEW PRINT,https://bsu.bncollege.com/c/Financial-Accounti...,9.781264e+12,$107.90
3,334_1_9,201,03,FINANCIAL ACCOUNTING: INFORMATION FOR DECISION...,10TH 21,MCG CUSTOM,NEW PRINT,https://bsu.bncollege.com/c/Financial-Accounti...,9.781264e+12,$107.90
4,334_1_9,201,04,FINANCIAL ACCOUNTING: INFORMATION FOR DECISION...,10TH 21,MCG CUSTOM,NEW PRINT,https://bsu.bncollege.com/c/Financial-Accounti...,9.781264e+12,$107.90
...,...,...,...,...,...,...,...,...,...,...
992670,106757452,106762860,106737761,BIOL 252 LAB PRINTED ACCESS CODE,W21,VAN-GRINER,BUY NEW,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9.781646e+12,$45.60
992671,106757452,106762860,106737762,BIOL 252 LAB PRINTED ACCESS CODE,W21,VAN-GRINER,BUY NEW,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9.781646e+12,$45.60
992672,106757452,106762860,106737763,BIOL 252 LAB PRINTED ACCESS CODE,W21,VAN-GRINER,BUY NEW,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9.781646e+12,$45.60
992673,106757452,106762860,106737764,BIOL 252 LAB PRINTED ACCESS CODE,W21,VAN-GRINER,BUY NEW,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9.781646e+12,$45.60
992674,106757452,106762860,106737765,BIOL 252 LAB PRINTED ACCESS CODE,W21,VAN-GRINER,BUY NEW,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9.781646e+12,$45.60

In [28]:
# Drop any rows where title, ISBN, and price are ALL missing (i.e., not much use for analysis)

df2 = df2.dropna(axis=0, subset=["title", "ISBN", "price"], how="all")

In [29]:
# Fill in missing values with default values  

df2 = df2.fillna(value={"edition":"unknown", "publisher":"unknown", "ISBN": 0.0, "price":"0.01"})

In [30]:
# Rename ISBN column to isbn 

df2 = df2.rename(columns={"ISBN":"isbn"})

In [31]:
# Transform isbn data

df2["isbn"] = clean_isbns(df2["isbn"])

In [32]:
# Transform price data

df2["price"] = clean_prices(df2["price"])

In [33]:
# Take a random sample of our dataframe to see if transformations are effective

df2.sample(50)

,department_id,course_id,section_id,title,edition,publisher,book_type,book_url,isbn,price
187111,774_1_540,499,1003,EMPIRICAL RESEARCH AND WRITING: A POLITICAL SC...,15,SAGE,USED PRINT,https://unlv.bncollege.com/c/Empirical-Researc...,9781483369631,33.75
767548,52_52_901,322,02,WRITER'S NOTEBOOK: UNLOCKING THE WRITER WITHIN...,96,HARP PUB,NEW PRINT RENTAL,https://wsubookie.bncollege.com/c/Writers-Note...,9780380784301,4.30
669258,740_1_740,2000,32152,PEACE AND CONFLICT STUDIES,5TH 22,SAGE,USED PRINT,https://wayne.bncollege.com/c/Peace-and-Confli...,9781544369051,93.75
879742,106757311,106763509,106737815,LABORATORY NOTEBOOK 50PG,LATEST,LAD CUSTOM,BUY NEW,https://unc.bncollege.com/shop/unc/textbook/la...,978193869536,11.69
45684,738_738_498,AIDS,01,MEDICAL TERMINOLOGY BODY SYSTEMS: QUICK STUDY ...,00,BARCHARTS,NEW PRINT,https://binghamton.bncollege.com/c/Medical-Ter...,9781572225411,6.95
579883,370_370_105,100,0105,CRIMINAL JUSTICE IN AMERICA,9TH 18,CENGAGE L,USED PRINT,https://umcp.bncollege.com/c/Criminal-Justice-...,9781305966062,124.69
786720,707_1_380,X3207,001,HEREMAKHONON,82,RIENNER,NEW PRINT RENTAL,https://columbia.bncollege.com/c/Heremakhonon/...,978089410886,15.90
644043,619_1_330,02110,2,"BEOWULF - A NEW VERSE TRANSLATION, BILINGUAL E...",00,NORTON,DIGITAL PURCHASE,https://rowanbookstore.bncollege.com/c/Beowulf...,9780393320978,14.95
254431,336_1_280,4593,25667,ACHIEVING SOCIAL EQUITY,20,MELVIN+L,NEW PRINT RENTAL,https://uco.bncollege.com/c/Achieving-Social-E...,9781733934466,35.45
379343,8159_1_152,113,025,CHEM. 113: GEN. CHEM. II LAB ACCESS,unknown,CHEM21,NEW PRINT,https://uky.bncollege.com/c/CHEM-113-GEN-CHEM-...,2818440008603,46.46
147796,246_1_204,154,001,FOR COLORED GIRLS WHO HAVE CONSIDERED SUICIDE ...,10,S+S,NEW PRINT,https://ilstu.bncollege.com/c/For-Colored-Girl...,9780684843261,12.99
989302,105073248,105075572,105061905,PRACTICE OF HARMONY (LOOSELEAF),7TH 18,PEARSON,RENT DIGITAL,https://troy.bncollege.com/shop/BNCB_TextbookD...,9780133785203,44.99
133832,246_1_95,102,009,ESSENTIALS OF GEOLOGY - TEXT ONLY,6TH 19,NORTON,NEW PRINT,https://ilstu.bncollege.com/c/Essentials-of-Ge...,9780393644456,134.50
160444,774_1_315,200,1003,BIOSTATISTICS FOR BIOLOGICAL AND HEALTH SCIENC...,2ND 18,PEARSON CO,DIGITAL PURCHASE,https://unlv.bncollege.com/c/Biostatistics-for...,8220117023422,82.31
491313,572_1_184,215,500,WORLD CINEMA: A CRITICAL INTRODUCTION,18,TAYLOR,USED PRINT RENTAL,https://tamu.bncollege.com/c/World-Cinema-A-Cr...,9780415783576,29.60
479418,370_370_32,323,FC01,HEALTH PROMOTION IN DISEASE,unknown,TAYLOR,NEW PRINT,https://umcp.bncollege.com/c/HEALTH-PROMOTION-...,9781138093171,44.95
335134,353_1_10,0508,002,"BUSINESS ASSOCIATIONS, CASES AND MATERIALS ON ...",10TH 18,WEST ACAD,NEW PRINT,https://temple.bncollege.com/c/Business-Associ...,9781683285229,282.88
356880,8152_1_557,26001,004,WRITING TIPS AND TRICKS,12,BARCHARTS,USED PRINT,https://kent.bncollege.com/c/Writing-Tips-and-...,9781423217763,5.21
493577,446_446_71,250W,001,ESSENTIALS OF RESEARCH METHODS FOR CRIMINAL JU...,3RD 12,PEARSON,USED PRINT,https://psu.bncollege.com/c/Essentials-of-Rese...,9780135121009,103.99
820592,707_1_575,G8206,001,"BLACK SKIN, WHITE MASKS",67,INGRAM PUB,USED PRINT,https://columbia.bncollege.com/c/Black-Skin-Wh...,9780802150844,10.50
257504,244_1_710,1600,10350,INTERNATIONAL RELATIONS,11TH 17,PEARSON,NEW PRINT RENTAL,https://oakland.bncollege.com/c/International-...,9780134404769,168.65
734304,620_1_370,371,901,PSYCHOLOGY OF EXERCISE: INTEGRATING THEORY AND...,5TH 20,TAYLOR,USED PRINT,https://vcu.bncollege.com//Textbooks/Psycholog...,9780367186807,63.71
449919,572_1_96,315,200,QUANTITATIVE CHEMICAL ANALYSIS,10TH 20,MAC HIGHER,NEW PRINT RENTAL,https://tamu.bncollege.com/c/Quantitative-Chem...,97813191643,231.70
407621,396_1_715,1022,012,ALGEBRA AND TRIGONOMETRY - MYLABMATH ACCESS (1...,3RD 19,PEARSON CO,DIGITAL PURCHASE,https://lsu.bncollege.com/c/Algebra-and-Trigon...,8220117017063,76.43
178030,8011_1_375,100W,03,PUBLICATION MANUAL OF THE AMERICAN PSYCHOLOGIC...,7TH 20,AM PSYCHOL,USED PRINT,https://sjsu.bncollege.com/c/Publication-Manua...,9781433832161,24.32
567652,240_1_445,314,001,"DEVIL IN THE WHITE CITY: MURDER, MAGIC, AND MA...",03,PENG RAND,USED PRINT RENTAL,https://sc.bncollege.com/Textbooks/Devil-in-th...,9780375725609,8.40
256913,244_1_690,1610,12225,PRINCIPLES AND PHYSICS - WEBASSIGN (MULTI),5TH 13,CENGAGE L,NEW PRINT,https://oakland.bncollege.com/c/Principles-and...,9781337770828,156.25
612102,370_370_405,202,0201,NIHONGO NOW LEVEL 2 VOL 1 + ACTIVITY BK,2021,TAYLOR,USED PRINT,https://umcp.bncollege.com/c/NIHONGO-NOW-LEVEL...,9780367743543,65.10
336123,330_1_559,900,390,INTRODUCING THEOLOGICAL METHOD: A SURVEY OF CO...,17,BAKER PUB,USED PRINT RENTAL,https://liberty.bncollege.com/c/Introducing-Th...,9780801049491,8.80
335928,330_1_559,201,005,INTRODUCING CHRISTIAN DOCTRINE,3RD 15,BAKER PUB,USED PRINT RENTAL,https://liberty.bncollege.com/c/Introducing-Ch...,9780801049194,13.15
514158,572_1_276,120,876,SKYEPACK KINE 120 CURRIC.+SPORT PACK >I,NON-EXP,SKYEPACK,NEW PRINT,https://tamu.bncollege.com/c/SKYEPACK-KINE-120...,2819480261102,58.67
750227,707_1_47,W1010,001,FEDERALIST PAPERS,03,PENG RAND,NEW PRINT RENTAL,https://columbia.bncollege.com/c/Federalist-Pa...,978045152881,5.40
149710,246_1_45,215,001,QUANTITATIVE CHEMICAL ANALYSIS,10TH 20,MAC HIGHER,USED PRINT,https://ilstu.bncollege.com/c/Quantitative-Che...,97813191643,255.53
957796,104911989,105047898,105771882,PUBL.MAN.OF AM.PSYCH.ASSOC. (SP),7TH 20,AM PSYCHOL,BUY USED,https://shsu.bncollege.com/shop/BNCB_TextbookD...,9781433832178,33.74
29105,738_738_335,281G,01,HISTORIES,98,OXF,DIGITAL RENTAL,https://binghamton.bncollege.com/c/Histories/p...,9780199535668,3.50
596286,370_370_255,394,9011,ON WRITING WELL: CLASSIC GUIDE TO WRITING NONF...,REV 06,HARP PUB,NEW PRINT,https://umcp.bncollege.com/c/On-Writing-Well-C...,9780060891541,17.99
914548,105161088,106428443,106427577,PSYCHOMETRICS,4TH 22,SAGE,RENT NEW,https://fiu.bncollege.com/shop/BNCB_TextbookDe...,9781071824078,98.75
363299,8152_1_605,20040,001,NURSING CARE PLANS: GUIDE.. SPAN,10TH 19,DAVIS FA C,DIGITAL PURCHASE,https://kent.bncollege.com/c/Nursing-Care-Plan...,9781719642675,61.95
656187,740_1_742,3050,24250,GREAT PRETENDER: THE UNDERCOVER MISSION THAT C...,19,HACHETTE B,USED PRINT RENTAL,https://wayne.bncollege.com/c/Great-Pretender-...,9781538715284,12.35
160411,8011_1_235,112,01,GUIDE TO CLINICAL ASSESSMENT AND PROFESSIONAL ...,2ND 18,SLACK,USED PRINT,https://sjsu.bncollege.com/c/Guide-to-Clinical...,9781630913724,72.92
871977,106757844,106761387,106744181,ESSENTIALS OF HEALTH JUSTICE,19,JONES+BART,RENT USED,https://unc.bncollege.com/shop/BNCB_TextbookDe...,9781284152074,20.70
241072,632_632_398,130,19872,STAGE MAKEUP,11TH 19,TAYLOR,DIGITAL RENTAL,https://iub.bncollege.com/c/Stage-Makeup/p/MBS...,9780367183325,48.72
77151,490_1_308,2020,002,ON DUTIES,16,LONGLEAF,USED PRINT,https://clemson.bncollege.com/c/On-Duties/p/MB...,9781501704529,19.46
371151,693_1_190,0852,705,REPUBLIC,04,HACKETT,DIGITAL PURCHASE,https://temple.bncollege.com/c/Republic/p/MBS_...,9780872207363,12.75
278863,632_632_393,141,8220,INTRODUCTION TO SOCIAL WORK: AN ADVOCACY-BASED...,2ND 19,SAGE,USED PRINT RENTAL,https://iub.bncollege.com/c/Introduction-to-So...,9781506394534,59.25
778491,707_1_340,V3025,002,INVESTMENTS (LOOSELEAF),11TH 18,MCG,USED PRINT,https://columbia.bncollege.com/c/Investments-L...,9781259715204,274.91
151631,774_1_266,406B,1001,"SHAPED BY THE WEST, VOLUME 2: A HISTORY OF NOR...",18,INGRAM PUB,NEW PRINT,https://unlv.bncollege.com/c/Shaped-by-the-Wes...,9780520291416,34.95
652684,619_1_560,01131,9,CALCULUS: EARLY TRANSCENDENTALS,4TH 19,MAC HIGHER,NEW PRINT RENTAL,https://rowanbookstore.bncollege.com/c/Calculu...,978131905074,178.00
812105,276_1_430,3051,001,SAVING GRACE,95,PENG RAND,NEW PRINT,https://charlotte.bncollege.com/c/Saving-Grace...,9780345403339,13.95
874740,107485453,107486119,107484928,HEALTH CARE INFORMATION SYSTEMS,4TH 17,WILEY,BUY NEW,https://fiu.bncollege.com/shop/fiu/textbook/he...,9781119337188,117.86

In [34]:
# Examine dtypes and value_counts for columns

print(f"DATA TYPES:\n\n{df2.dtypes}\n\n")

for col in df2.columns.tolist():
    print(f"COLUMN: {col}\n")
    print(f"=================================\n")
    print(vc(df2[col]))
    print(f"\n\n")

DATA TYPES:

department_id     object
course_id         object
section_id        object
title             object
edition           object
publisher         object
book_type         object
book_url          object
isbn              object
price            float64
dtype: object


COLUMN: department_id

=================================

             department_id
707_1_505             4897
707_1_260             4692
693_1_190             4237
334_1_908             3106
656_1_805             2463
...                    ...
441_441_127              1
103683120                1
51_51_26                 1
107330936                1
50_1_120                 1

[8099 rows x 1 columns]



COLUMN: course_id

=================================

           course_id
101             8074
102             6329
201             5304
200             4748
C1102           4579
...              ...
106112662          1
106112664          1
106112665          1
106112666          1
105482859          1

[19615 rows x 1 columns]



COLUMN: section_id

=================================

           section_id
001             92423
01              37982
002             23087
0101            11609
003             11279
...               ...
105149959           1
107319902           1
107319903           1
107319904           1
106737765           1

[40781 rows x 1 columns]



COLUMN: title

=================================

                                                    title
PUBLICATION MANUAL OF THE AMERICAN PSYCHOLOGICA...   7329
CENGAGE UNLIMITED - ACCESS (1 SEMESTER)              1616
PUBL.MAN.OF AM.PSYCH.ASSOC. (PB)                     1293
ICLICKER2 STUDENT REMOTE REV.                        1208
FIRST DAYS OF SCHOOL: HOW TO BE AN EFFECTIVE TE...    984
...                                                   ...
UNDERSTANDING PATHOPHYSIO+EVOLVE CDE>BI                 1
CHEM 51B W20 KING NOTES (CUSTOM)                        1
INTRO TO CRIMINOLOGY - EBOOK ACCSS                      1
A CRITICAL HISTORY OF GERMAN FILM, SECOND EDITION       1
WATERCOLOR-BURNT SIENNA-7.5ML                           1

[55406 rows x 1 columns]



COLUMN: edition

=================================

        edition
18        17523
17        16327
7TH 20    15090
20        14404
16        13837
...         ...
866739        1
865559        1
868589        1
20-21         1
PRE           1

[1059 rows x 1 columns]



COLUMN: publisher

=================================

            publisher
PEARSON         56724
PENG RAND       50551
CENGAGE L       37696
WILEY           31315
MAC HIGHER      31214
...               ...
U OF WI CC          1
ANANSI CC           1
SAGE AC CC          1
NEW SOC CC          1
EAT RIGHT           1

[2092 rows x 1 columns]



COLUMN: book_type

=================================

                   book_type
NEW PRINT             176916
USED PRINT            137171
NEW PRINT RENTAL       99688
USED PRINT RENTAL      98007
DIGITAL PURCHASE       28571
BUY NEW                22884
BUY USED               16150
DIGITAL RENTAL         15088
RENT NEW               12781
RENT USED              12536
BUY DIGITAL            10627
COURSE MATERIAL         6042
RENT ONLY               4452
RENT DIGITAL            4342



COLUMN: book_url

=================================

                                                    book_url
https://liberty.bncollege.com/c/Praise-Effectiv...       330
https://liberty.bncollege.com/c/Praise-Effectiv...       330
https://liberty.bncollege.com/Textbooks/First-D...       330
https://liberty.bncollege.com/Textbooks/First-D...       330
https://vcu.bncollege.com//c/We-Have-Always-Liv...       280
...                                                      ...
https://umcp.bncollege.com/c/Shattered--Reclaim...         1
https://umcp.bncollege.com/c/Shattered--Reclaim...         1
https://umcp.bncollege.com/c/Rip-in-Heaven--Mem...         1
https://umcp.bncollege.com/c/Rip-in-Heaven--Mem...         1
https://unc.bncollege.com/shop/BNCB_TextbookDet...         1

[241446 rows x 1 columns]



COLUMN: isbn

=================================

               isbn
9781433832161  8620
9780357700006  1668
9781498603041  1208
9780976423386  1047
9780890425558   828
...             ...
8220107270942     1
82201066863       1
8220103634168     1
8220103634151     1
9781319343958     1

[59232 rows x 1 columns]



COLUMN: price

=================================

       price
0.01    6355
6.95    5341
44.99   4187
74.99   4037
5.21    3297
...      ...
9.22       1
74.22      1
73.11      1
21.19      1
21.78      1

[14764 rows x 1 columns]

In [39]:
# Render some columns as categorical data type - saves memory

# df1.loc[ : , ("term")  ].astype("category")

df2.loc[   :   , ("book_type")  ].astype("category")
df2.loc[   :   , ("edition")    ].astype("category")
df2.loc[   :   , ("publisher")  ].astype("category")
df2.loc[   :   , ("isbn")       ].astype("category")
df2.loc[   :   , ("title")      ].astype("category")

df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645255 entries, 0 to 992674
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   department_id  645255 non-null  object
 1   course_id      645255 non-null  object
 2   section_id     645255 non-null  object
 3   title          645255 non-null  object
 4   edition        645255 non-null  object
 5   publisher      645255 non-null  object
 6   book_type      645255 non-null  object
 7   book_url       645255 non-null  object
 8   isbn           645255 non-null  object
 9   price          645255 non-null  float64
dtypes: float64(1), object(9)
memory usage: 54.2+ MB

In [ ]:
df2 = df2.reset_index(drop=True)

In [ ]:
textbooks_df = df2.copy()

In [ ]:
textbooks_df.head(5)

In [ ]:
textbooks_df.sample(50)

In [ ]:
# Render as csv file for import into PostGresSQL

textbooks_df.to_csv("MERGE_textbooks.csv", encoding="utf-8")

# 172 MB csv

# Merge courses and textbooks dataframes with inner join

### *merge_courses_and_textbooks_df*

In [ ]:
# Inner merge on both dataframes on common id fields

merge_df = pd.merge(courses_df, textbooks_df, on=["department_id", "course_id", "section_id"], how="inner")

In [ ]:
merge_df.info()

In [ ]:
merge_df.drop_duplicates()

In [ ]:
merge_df.sample(50)

In [ ]:
merge_df = merge_df.reset_index(drop=True)

In [ ]:
merge_df.info()

In [ ]:
merge_courses_and_textbooks = merge_df.copy()

In [ ]:
# Render as csv file for import into PostGresSQL


merge_courses_and_textbooks.to_csv("MERGE_courses_and_textbooks.csv", encoding="utf-8")

In [ ]:
# 219 MB csv